version: "2"
services:
  daemon:
    build: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV
      - KEY
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"