version: "2"
services:
  node:
    image: "node:11"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=testnet
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"