openapi: 3.0.0
info:
  description: "SWC specification"
  version: "1.0.0"
  title: "SWC specification"
  contact:
    email: ""
servers:
  - url: http://localhost:3000/api/v1
    description: Localhost (uses test data)

paths:
  /status:
    get:
      description: Status route, so we can check if server is alive
      tags:
        - Status
      responses:
        200:
          description: "Server is alive"
          content:
            application/json:
              schema:
                type: object
                properties:
                  health:
                    type: boolean
                  date:
                    type: string
                example:
                  health: true
                  date: "2018-02-19T15:36:46.758Z"
  /metaTxRelay:
    post:
      description: "test"
      tags:
        - Status
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  pattern: ^[0-9a-fA-F]+$
                  example: "0xd2330a9f6dde4715f540d1669bf75e89a1b4fbbc"
                to:
                  type: string
                  pattern: ^[0-9a-fA-F]+$
                  example: "0x7d0344e0ee6bc3901f4b11b9d9b8d001b49872a1"

                amount:
                  type: string
                  example: "200000000"
                  description: "using BigNumber"
                inputs:
                  type: array
                  example: ["20000000", "2222", "40000", "3000"]
                  items:
                    type: string
                    description: "using BigNumber [0 => _gasPrice, 1 => _gasLimit, 2 => _gasTokenPerWei, 3 => _nonce]"
                relayer:
                  type: string
                  pattern: ^[0-9a-fA-F]+$
                  example: "0x9780991cb8c857f0fa2f96020abe3bc410f97b26"
                tokenReceiver:
                  type: string
                  pattern: ^[0-9a-fA-F]+$
                  example: "0x9780991cb8c857f0fa2f96020abe3bc410f97b26"
                sig:
                  type: string
                  pattern: ^[0-9a-fA-F]+$
                  example: "0x9780991cb8c857f0fa2f96020abe3bc410f97b26"

      responses:
        201:
          description: Created
