openapi: 3.0.0
info:
  description: "Swingby Witness Component(SWC) specification"
  version: "1.0.0"
  title: "swc specification"
  contact:
    email: ""
servers:
  - url: http://localhost:3000/api/v1
    description: Localhost (uses test data)

paths:
  /status:
    get:
      description: Status route, so we can check if server is alive
      tags:
        - Status
      responses:
        200:
          description: "Server is alive"
          content:
            application/json:
              schema:
                type: object
                properties:
                  health:
                    type: boolean
                  date:
                    type: string
                example:
                  health: true
                  date: "2018-02-19T15:36:46.758Z"
  /metaTxRelay/{tokenAddress}:
    get:
      parameters:
        - in: path
          name: tokenAddress # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: The token address
      description: "test"
      tags:
        - Status
      responses:
        200:
          description: GET
    post:
      parameters:
        - in: path
          name: tokenAddress # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: The token address
      description: "test"
      tags:
        - Status
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  required: true
                  example: "0xd2330a9f6dDe4715F540D1669bf75E89a1b4FbBc"
                to:
                  type: string
                  required: true
                  example: "0x7D0344e0ee6bC3901F4b11b9d9b8D001b49872A1"

                amount:
                  type: string
                  required: true
                  example: "20000000000000000000"
                  description: "using BigNumber"
                inputs:
                  type: array
                  example: ["4000000000", "200000", "100000000000000000", "1"]
                  items:
                    type: string
                    required: true
                    description: "using BigNumber [0 => _gasPrice, 1 => _gasLimit, 2 => _gasTokenPerWei, 3 => _nonce]"
                providers:
                  type: array
                  example: ["0xb38f6C9d887b038038aa0272a4cd15c75B28E781", "0xCC8690540faE802A251945556817D49a96990f44"]
                  items:
                    type: string
                    required: true
                    description: "[0 => _relayer, 1 => _tokenReceiver"
                v:
                  type: string
                  required: true
                  example: "28"
                r:
                  type: string
                  required: true
                  example: "0x523863f32e497899d5d2c2fb6855f7da76fd9fa3927af887a0d21f352383f430"
                s:
                  type: string
                  required: true
                  example: "0x701097c72f6b46efcdd65ecb34d859e97e88ed4952c36f1d8aa18171ec215208"

      responses:
        201:
          description: Created
