openapi: 3.0.0
info:
  version: "1.0.0"
  title: "SWC Basic API specification"
  description: "Swingby Witness Component(SWC) specification"
  contact:
    email: ""
servers:
  - url: http://35.247.144.116:3000/api/v1
  - url: http://localhost:3000/api/v1
    description: Dev

paths:
  /wshLists:
    get:
      tags:
        - Status
      responses:
        200:
          description: GET
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
                  wshLists:
                    type: array
                    items:
                      type: object
                      properties:
                        wsh:
                          type: string
                        own:
                          type: string
                    example:
                      - wsh: "0xba59e076ba94b354d0050e1339e50723370afd8fcb9dfd274c026e3816f82a9b"
                        own: "0xb38f6C9d887b038038aa0272a4cd15c75B28E781"
                      - wsh: "0xc1d3260b34dd0784e58da35164ad7340ff8ba9cc57ad6a1fa924fe212b5337d0"
                        own: "0x7D0344e0ee6bC3901F4b11b9d9b8D001b49872A1"
  /wshLists/{wsh}:
    get:
      parameters:
        - in: path
          name: wsh # Note the name is the same as in the path
          required: true
          schema:
            type: string
          example: "0x0cea2bc57addc0ca4a6f2fce7dc16d9de55db1944ce4746f541d9d0b7a7d1a2e"
          description: get status of wsh. status = ["NotUsed", "UsedByLender", "UsedByBoth", "Approved"]
      description: Status route, so we can check if server is alive
      tags:
        - Status
      responses:
        200:
          description: GET
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
                  wshLists:
                    type: array
                    items:
                      type: object
                      properties:
                        wsh:
                          type: string
                        own:
                          type: string
                    example:
                      - wsh: "0xba59e076ba94b354d0050e1339e50723370afd8fcb9dfd274c026e3816f82a9b"
                        own: "0xb38f6C9d887b038038aa0272a4cd15c75B28E781"
                      - wsh: "0xc1d3260b34dd0784e58da35164ad7340ff8ba9cc57ad6a1fa924fe212b5337d0"
                        own: "0x7D0344e0ee6bC3901F4b11b9d9b8D001b49872A1"


  /metaTxRelay/{gasToken}:
    get:
      parameters:
        - in: path
          name: gasToken # Note the name is the same as in the path
          required: true
          schema:
            type: string
          example: "0x142c68565b6cda5EE19d1aE704A0Bbe80f43c0A8"
          description: The gasToken address
        - in: query
          name: signer
          required: true
          example: "0xd2330a9f6dDe4715F540D1669bf75E89a1b4FbBc"
          schema:
            type: string
          description: address of EOA signer
        - in: query
          name: salt
          required: true
          example: "0x2076aeb"
          schema:
            type: string
          description: hexstring of randam salt of your contract account
      description: "test"
      tags:
        - Status
      responses:
        200:
          description: GET
          content:
            application/json:
              schema:
                example:
                  result: true
                  token:
                    address: "0x142c68565b6cda5EE19d1aE704A0Bbe80f43c0A8"
                  signer:
                    address: "0xd2330a9f6dDe4715F540D1669bf75E89a1b4FbBc"
                    wallet: "0x82b98AC337A3b2da0450c6BDac5E27f7E6D46960"
                    nextNonce: "1"
                  relayer:
                    address: "0xb38f6C9d887b038038aa0272a4cd15c75B28E781"
                    gasPrice: "4000000000"
                    gasLimit: "200000"
    post:
      parameters:
        - in: path
          name: gasToken # Note the name is the same as in the path
          required: true
          schema:
            type: string
          example: "0x142c68565b6cda5EE19d1aE704A0Bbe80f43c0A8"
          description: The gasToken address
      description: "test"
      tags:
        - Status
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                signer:
                  type: string
                  required: true
                  example: "0xd2330a9f6dDe4715F540D1669bf75E89a1b4FbBc"
                salt:
                  type: string
                  required: true
                  example: "34040555"
                to:
                  type: string
                  required: true
                  example: "0x142c68565b6cda5EE19d1aE704A0Bbe80f43c0A8"
                value:
                  type: string
                  required: true
                  example: "0"
                  description: "using BigNumber basically use zero to call"
                data:
                  type: string
                  example: "0xa9059cbb0000000000000000000000007d0344e0ee6bc3901f4b11b9d9b8d001b49872a10000000000000000000000000000000000000000000000022b1c8c1227a00000"
                  required: true
                  description: "data payload to call other contract"
                nonce:
                  type: string
                  example: "1"
                  required: true
                  description: "signer's nonce"
                gasPrice:
                  type: string
                  example: "2000000000"
                  required: true
                  description: "gasPrice"
                safeTxGas:
                  type: string
                  required: true
                  example: "1500000"
                sig:
                  type: string
                  required: true
                  example: "0xe41a6f641594042fc98ecfb0becec85c3aa57f57307bfeb2cfd55614ce0989b811db8cdd47b24fd227405bbe4928141c98d92e58f0d753f92c1680bb5d9124e21c"

      responses:
        200:
          description: OK

  /submitLenderTxRelay/{tokenAddress}:
